version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: biblioteca_mysql
    environment:
      MYSQL_ROOT_PASSWORD: biblioteca123
      MYSQL_DATABASE: biblioteca_db
      MYSQL_USER: biblioteca_user
      MYSQL_PASSWORD: biblioteca_pass
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

volumes:
  mysql_data:
